contact_manager/config/routes.rb
ContactManager::Application.routes.draw do
  resources :companies
  resources :phone_numbers
  resources :people do
  end

  get '/auth/:provider/callback' => 'sessions#create'
  get '/login' => redirect('/auth/twitter')
  delete '/logout' => "sessions#destroy"

  root to: "site#index"

end

contact_manager/app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true

  has_many :phone_numbers, as: :contact

end

contact_manager/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

contact_manager/app/helpers/companies_helper.rb
module CompaniesHelper

  def hello_tag
    content_tag :div, class: "hello" do
      "!!!!! COMPANY !!!! REALLY, you're looking for me!"
    end
  end


end

contact_manager/app/views/companies/_company_carousel.html.erb
<script type="text/javascript">
$("#linklink").carousel({ images: [ '<%= asset_path('important.png') %>' ] })
</script>

contact_manager/app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

contact_manager/app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

contact_manager/app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

contact_manager/app/views/companies/index.html.haml
%h1 Listing companies
%a{href: "#",style: "color: red;", "data-element" => 'linklink'} Click Me!

%div{class: "mystuff red color main", id: "companies-header"} Text
%div.mystuff.red.color.main{id: "companies-header"} Text
%div.mystuff.red.color.main#companies-header Text
.mystuff.red.color.main#companies-header Text

%table
  %tr
    %th Name
    %th Show
    %th Edit
    %th Destroy

  - @companies.each do |company|
    %tr
      %td= company.name
      %td
        = link_to 'Show', company
      %td
        = link_to 'Edit', edit_company_path(company)
      %td
        = link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Company', new_company_path
= render partial: 'company_carousel'

contact_manager/app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

contact_manager/app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<div class="phone-numbers">

  <% @company.phone_numbers.each do |phone_number| %>
    <p id="<%= dom_id(phone_number) %>">
      <b>Phone:</b>
      <%= phone_number.number %>
    </p>
  <% end %>

  <%= link_to 'Add phone number', new_phone_number_path(contact_id: @company.id,contact_type: @company.class) %>

</div>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>